Updated cuationary note about screens using Astro 4
RocketCommunicationsInc/astro-uxds pull request #125
Opened 2020-12-14 18:06 UTC by dmcalester

Added a banner to service specific designs noting screens should not be used for color/font. Adding links after draft-pr generates preview

2020-12-14 20:05 UTC, carmenparks commented
@dmcalester Awkward/repetitive working of this sentence:
"All new projects should use Astro 5 colors and fonts should be used for compliant Astro applications."

Suggest removing words in bold: All new projects should use Astro 5 colors and fonts **should be used** for compliant Astro applications.

Also needs space after the period at the end of this sentence.

2020-12-14 20:06 UTC, carmenparks requested changes
Left comment re: repetitive wording and needing space after end of sentence.

2020-12-14 21:07 UTC, amalyah requested changes

2020-12-14 21:07 UTC, amalyah commented on _content/grm-service-ux-design/about-the-grm-designs.md
> +The images depicted on this page use the color palette and fonts from Astro 4. All new projects should use Astro 5 colors and fonts should be used for compliant Astro applications.Refer to this secti
Same as Carmen's comment for this line, but the sentence at the end of the paragraph needs a period too. Needs to be updated on all instances.

2020-12-14 21:08 UTC, amalyah commented
Which Jira ticket does this PR link to @dmcalester?

2020-12-14 21:32 UTC, Design-Kat commented
"All new projects should use Astro 5 colors and fonts should be used for compliant Astro applications."
This sentence feels incomplete and the meaning isn't quite clear. I'm not sure if you're talking about the same "new projects" on the first and second half or if one is for new and one is for old? Suggest a bit of a tweak to how it's written. If they're the same "All new projects should Use Astro 5 colors and font to be considered a compliant Astro application." or if referring to New vs Established applications consider rewording to something like, "All new projects should Use Astro 5. Currently compliant Astro Applications should Use Astro 5 colors and fonts."

2020-12-14 21:34 UTC, Design-Kat requested changes
See comment on about-the-grm-designs.

2020-12-14 21:34 UTC, Design-Kat commented on _content/grm-service-ux-design/about-the-grm-designs.md
> +The images depicted on this page use the color palette and fonts from Astro 4. All new projects should use Astro 5 colors and fonts should be used for compliant Astro applications.Refer to this secti
"All new projects should use Astro 5 colors and fonts should be used for compliant Astro applications."
This sentence feels incomplete and the meaning isn't quite clear. I'm not sure if you're talking about the same "new projects" on the first and second half or if one is for new and one is for old? Suggest a bit of a tweak to how it's written. If they're the same "All new projects should Use Astro 5 colors and font to be considered a compliant Astro application." or if referring to New vs Established applications consider rewording to something like, "All new projects should Use Astro 5. Currently compliant Astro Applications should Use Astro 5 colors and fonts."

2020-12-15 20:31 UTC, Design-Kat requested changes
Only change I see is that the 's' on Applications should be removed, or the 'an' removed to make the plural applications make sense - other than that it looks great!

2020-12-15 21:28 UTC, amalyah approved these changes

2020-12-15 21:37 UTC, amalyah commented
Jira ticket: https://rocketcom.atlassian.net/browse/ASTRO-970

2020-12-15 22:15 UTC, Design-Kat approved these changes

2020-12-15 22:38 UTC, merged