Updated all images in KM to 2x
RocketCommunicationsInc/astro-uxds pull request #134
Opened 2021-01-12 17:22 UTC by dmcalester

All images have been updated to 2x
Fixes ASTRO-1107 https://rocketcom.atlassian.net/browse/ASTRO-1107

2021-01-13 18:51 UTC, amalyah reviewed
- Broken image links on [Status System](https://deploy-preview-134--astrouxds.netlify.app/patterns/status-system/), [Navigation](https://deploy-preview-134--astrouxds.netlify.app/patterns/navigation/), [Theme](https://deploy-preview-134--astrouxds.netlify.app/design-guidelines/theme/), [Sample App](https://deploy-preview-134--astrouxds.netlify.app/patterns/sample-app/), and [Dialog Box](https://deploy-preview-134--astrouxds.netlify.app/components/dialog-box/) pages.

- Oversized images on [Compliance](https://deploy-preview-134--astrouxds.netlify.app/design-guidelines/compliance/) (4.6.6, 4.7.3, 4.10.2, 4.12.1, 4.12.2, 4.13.6, and 4.14.2) and [Accordion](https://deploy-preview-134--astrouxds.netlify.app/components/accordion/).

- Blurry images (not sure if we can do anything about them, but thought I'd note them) on: [Visual Design](https://deploy-preview-134--astrouxds.netlify.app/design-process/visual-design/), most of the [TT&C](https://deploy-preview-134--astrouxds.netlify.app/ttc-service-ux-design/about-the-ttc-designs/) pages, most of the [GRM](https://deploy-preview-134--astrouxds.netlify.app/grm-service-ux-design/about-the-grm-designs/) pages, the[ Service Specific](https://deploy-preview-134--astrouxds.netlify.app/service-specific-ux-design/) page, [Global Status Bar](https://deploy-preview-134--astrouxds.netlify.app/components/global-status-bar/), [Buttons](https://deploy-preview-134--astrouxds.netlify.app/components/button/), [Component Sandbox](https://deploy-preview-134--astrouxds.netlify.app/components/component-sandbox/), [UI Design](https://deploy-preview-134--astrouxds.netlify.app/design-process/ui-design/), and some blurry images on the [FD Service](https://deploy-preview-134--astrouxds.netlify.app/fd-service-ux-design/about-the-fd-designs/) page.

2021-01-13 18:51 UTC, amalyah commented on package.json
> +		"start:clean": "rimraf _site",
@dmcalester What does this change do?

2021-01-13 18:58 UTC, dmcalester commented on package.json
> +		"start:clean": "rimraf _site",
The Astro site gets built from templates (for structure/layout), markdown (for content) and static assets like images and compiled in to tradition HTML/CSS/JS structure in a `_site` directory. When testing locally the static assets can sometimes become stale, the content and code will update but an image might be out of date. `rimraf` deletes the `_site` directory so it gets rebuilt from scratch every time the local dev server starts.

2021-01-13 21:38 UTC, dmcalester commented
> * Broken image links on [Status System](https://deploy-preview-134--astrouxds.netlify.app/patterns/status-system/), [Navigation](https://deploy-preview-134--astrouxds.netlify.app/patterns/navigation/), [Theme](https://deploy-preview-134--astrouxds.netlify.app/design-guidelines/theme/), [Sample App](https://deploy-preview-134--astrouxds.netlify.app/patterns/sample-app/), and [Dialog Box](https://deploy-preview-134--astrouxds.netlify.app/components/dialog-box/) pages.

These should be fixed

> * Oversized images on [Compliance](https://deploy-preview-134--astrouxds.netlify.app/design-guidelines/compliance/) (4.6.6, 4.7.3, 4.10.2, 4.12.1, 4.12.2, 4.13.6, and 4.14.2) and [Accordion](https://deploy-preview-134--astrouxds.netlify.app/components/accordion/).

There is a temporary solution in place, it is not ideal, but not grievous enough to hold back launch

> * Blurry images (not sure if we can do anything about them, but thought I'd note them) on: [Visual Design](https://deploy-preview-134--astrouxds.netlify.app/design-process/visual-design/), most of the [TT&C](https://deploy-preview-134--astrouxds.netlify.app/ttc-service-ux-design/about-the-ttc-designs/) pages, most of the [GRM](https://deploy-preview-134--astrouxds.netlify.app/grm-service-ux-design/about-the-grm-designs/) pages, the[ Service Specific](https://deploy-preview-134--astrouxds.netlify.app/service-specific-ux-design/) page, [Global Status Bar](https://deploy-preview-134--astrouxds.netlify.app/components/global-status-bar/), [Buttons](https://deploy-preview-134--astrouxds.netlify.app/components/button/), [Component Sandbox](https://deploy-preview-134--astrouxds.netlify.app/components/component-sandbox/), [UI Design](https://deploy-preview-134--astrouxds.netlify.app/design-process/ui-design/), and some blurry images on the [FD Service](https://deploy-preview-134--astrouxds.netlify.app/fd-service-ux-design/about-the-fd-designs/) page.

Creating a ticket for addressing blurry images. https://rocketcom.atlassian.net/browse/ASTRO-1148

2021-01-14 19:37 UTC, rocket-github approved these changes

2021-01-14 19:38 UTC, cskerbo approved these changes

2021-01-14 19:49 UTC, amalyah requested changes
- Still seeing accordion icons as larger than they are on the live site.
- For compliance: the max 50% width rule works well for some images, but not others. Would it be worth putting in exceptions for 4.5.3 and 4.6.3? Those images are now too small to give any value to the page in my opinion. Not worth delaying a deploy, but something to think about. May be better at that point just to remove the image from that page altogether.

2021-01-15 23:03 UTC, merged