Hot fixes
RocketCommunicationsInc/astro-uxds pull request #146
Opened 2021-02-22 20:26 UTC by dmcalester

Fix for [ASTRO-1264 Sticker sheets listed but not available](https://rocketcom.atlassian.net/browse/ASTRO-1264)
Fix for [ASTRO-900 Astro Website - incorrect images on Service Specific page](https://rocketcom.atlassian.net/browse/ASTRO-900)
Fix for [ASTRO-800 Push button guidance missing from Astro UXDS](https://rocketcom.atlassian.net/browse/ASTRO-800)

2021-02-22 20:42 UTC, rocketjeff approved these changes

2021-02-22 20:52 UTC, amalyah approved these changes
Approved, but we should make some other bug tickets if we don't fix some of the things I commented on in this hot fix branch.

2021-02-22 20:52 UTC, amalyah commented on _content/downloads.md
>  - Astro Sketch Dark Library ([Git Repository](https://github.com/RocketCommunicationsInc/astro-design-resources/tree/master/Sketch))
In the Git Repository, it looks like we have a Light Library file as well now. Could you please add that link in as well for consistency? (not blocking approval)

2021-02-22 20:52 UTC, amalyah commented on _content/downloads.md
> +- Astro Adobe XD Wireframe Library ([Git Repository](https://github.com/RocketCommunicationsInc/astro-design-resources/raw/863e6cf9e815d185073070ef9bec5aeecd12d9af/Adobe%20XD/Astro%205%20Wireframe%20
Do we want to keep the links to the XD libraries up since we know they have issues that we're not fixing? Or should we at least make a note that they're outdated/deprecated? (not blocking approval)

2021-02-22 20:52 UTC, amalyah commented on _content/service-specific-ux-design.md
>  [][ttc-monitor]
Missing link (didn't exist before though, so wouldn't technically block approval...but then we'd  need  to make another bug ticket)

2021-02-22 20:52 UTC, amalyah commented on _content/service-specific-ux-design.md
>  [][ttc-command]
Missing link (didn't exist before though, so wouldn't technically block approval...but then we'd  need  to make another bug ticket)

2021-02-22 20:54 UTC, amalyah requested changes
Storybook readme for Push Buttons needs to be updated with new UXDS URL

2021-02-22 22:16 UTC, dmcalester commented on _content/downloads.md
> +- Astro Adobe XD Wireframe Library ([Git Repository](https://github.com/RocketCommunicationsInc/astro-design-resources/raw/863e6cf9e815d185073070ef9bec5aeecd12d9af/Adobe%20XD/Astro%205%20Wireframe%20
Going to keep for the time being, but address in the future.
https://rocketcom.atlassian.net/browse/ASTRO-1265

2021-02-23 20:41 UTC, cskerbo approved these changes

2021-02-23 21:08 UTC, merged