Astro 983 update button compliance
RocketCommunicationsInc/astro-uxds pull request #149
Opened 2021-02-25 22:13 UTC by Design-Kat

Added compliance language to compliance.json
Added new rule of thumbs based on compliance language to button.md

2021-02-25 22:23 UTC, Design-Kat commented
@dmcalester @Cheshire89 - Just finished this up, though I don't seem to have permission to add reviewers. Can @amalyah be added as well please?

2021-02-26 15:49 UTC, amalyah requested changes

2021-02-26 15:49 UTC, amalyah commented on _content/_data/compliance.json
> +              "rule": "Primary buttons indicating preferred user actions shall be placed to the right of buttons used for secondary user actions when in Button groups.",
Needs consistent use of capitalization of buttons/Buttons. (Uses both here)

2021-02-26 15:49 UTC, amalyah commented on _content/components/button.md
> +- Position buttons consistently across the application. Unless there is a good reason not to, right-align buttons in Astro applications.
Could you update the "Do" terminology below to also use the term "right-align" instead  of 
"right justify"?

2021-02-26 15:49 UTC, amalyah commented on _content/_data/compliance.json
> +              "numeral": 9,
Does the version number of the compliance page need to be updated with this new change?

2021-02-26 15:49 UTC, amalyah commented on _content/components/button.md
> +- Position buttons consistently across the application. Unless there is a good reason not to, right-align buttons in Astro applications.
Also bonus points if you change the first Do/Don't from "User buttons" to "Use buttons". (Won't hold up approval  though)

2021-02-26 15:49 UTC, amalyah commented
@Design-Kat Can you update the description of the branch with the link to the Jira ticket?

2021-02-26 17:18 UTC, Design-Kat commented on _content/_data/compliance.json
> +              "numeral": 9,
@dmcalester Do I need to update the version number with the update?

2021-02-26 17:30 UTC, Design-Kat commented on _content/_data/compliance.json
> +              "numeral": 9,
@amalyah updated everything except for this, will wait on Duncan's reply.

2021-03-03 19:37 UTC, amalyah approved these changes
Approved pending the version number change. Also, as long as the "This branch is out-of-date with the base branch" warning I'm seeing in the checks list is resolved.

2021-03-09 17:47 UTC, dmcalester approved these changes

2021-03-09 17:47 UTC, dmcalester commented on _content/_data/compliance.json
> +              "numeral": 9,
@Design-Kat @amalyah yes, version will need to update. We can do it just prior to launch. https://rocketcom.atlassian.net/browse/ASTRO-1273

2021-03-10 17:33 UTC, merged