Update checkbox.md
RocketCommunicationsInc/astro-uxds pull request #152
Opened 2021-03-02 17:29 UTC by Design-Kat

Astro-581 added documentation for PI updates. Update Checkbox documentation/compliance.

https://rocketcom.atlassian.net/browse/ASTRO-581

2021-03-02 18:14 UTC, Design-Kat commented
@dmcalester @amalyah @Cheshire89 Please review when you get a chance for Astro-581.

2021-03-03 19:44 UTC, amalyah requested changes
- See comments for content edits
- Need to resolve "This branch is out-of-date with the base branch"
- Can't see preview since checks and deploy failed.

2021-03-03 19:44 UTC, amalyah commented on _content/components/checkbox.md
> +A basic Checkbox consists of a visual indicator of it's selected state followed by a label. Individual Checkboxes can appear selected (checked), Unselected (no check), and Disabled (no action can be
"its selected state"

2021-03-03 19:44 UTC, amalyah commented on _content/components/checkbox.md
> +![Do: Use parent checkboxes, when grouped, to select all, or select none.](/img/components/image.png "Do: Use parent checkboxes, when grouped, to select all, or select none.")
"when grouped, to select all or select none."

2021-03-03 19:44 UTC, amalyah commented on _content/components/checkbox.md
> +![Don’t: Group single checkboxes unless you have a good reason to do so.](/img/components/image.png "Group single checkboxes unless you have a good reason to do so.")
Unless you have a good reason to do what?

2021-03-04 16:46 UTC, Design-Kat commented on _content/components/checkbox.md
> +A basic Checkbox consists of a visual indicator of it's selected state followed by a label. Individual Checkboxes can appear selected (checked), Unselected (no check), and Disabled (no action can be
Fixed with last commit.

2021-03-04 16:46 UTC, Design-Kat commented on _content/components/checkbox.md
> +![Do: Use parent checkboxes, when grouped, to select all, or select none.](/img/components/image.png "Do: Use parent checkboxes, when grouped, to select all, or select none.")
Fixed with last commit.

2021-03-04 16:46 UTC, Design-Kat commented on _content/components/checkbox.md
> +![Don’t: Group single checkboxes unless you have a good reason to do so.](/img/components/image.png "Group single checkboxes unless you have a good reason to do so.")
Clarified text with last commit.

2021-03-04 16:56 UTC, Design-Kat commented
> * See comments for content edits
> * Need to resolve "This branch is out-of-date with the base branch"
> * Can't see preview since checks and deploy failed.

Fixed the updates.
It looks like Duncan had merged the draft branch with this, and so I believe the deploy and checks should pass now?

2021-03-04 17:02 UTC, amalyah approved these changes

2021-03-09 17:55 UTC, dmcalester commented on _content/components/checkbox.md
> +
Please close the two-col with a `:::` here

2021-03-09 18:00 UTC, dmcalester requested changes
One minor change to close out the second do/don't pair

2021-03-09 18:31 UTC, Design-Kat commented
> One minor change to close out the second do/don't pair

@dmcalester It looks like I missed 2 missing ":::" pairs, I fixed them both right away. Please see the latest commit for the update, thanks!

2021-03-10 17:58 UTC, merged