Update select.md
RocketCommunicationsInc/astro-uxds pull request #156
Opened 2021-03-04 20:42 UTC by Design-Kat

https://rocketcom.atlassian.net/browse/ASTRO-1159

Updated Rules of Thumb, description tweaked, and Appearance and Behavior section added.

2021-03-04 20:45 UTC, Design-Kat commented
@amalyah @dmcalester @Cheshire89 Please review when you have a moment. This is the documentation for Select. Thank you!

2021-03-08 21:14 UTC, amalyah requested changes

2021-03-08 21:14 UTC, amalyah commented on _content/components/select.md
> +- Items in a list should be ordered in a meaningful way, such as by value, alphabetical or recently selected.
alphabetical > alphabetically,
recently selected > by recently selected

2021-03-08 21:14 UTC, amalyah commented on _content/components/select.md
> +- List values should be a reasonable number, and avoid endless scrolling. Alternative components, such as Input Fields and Search (with autocomplete and appropriate validation) or [Table](/patterns/t
List values should be a reasonable number > Keep the number of list values to a reasonable number to avoid endless scrolling.

Missing links to Inputs and Search.

2021-03-08 21:14 UTC, amalyah commented on _content/components/select.md
> +- Do not remove disabled items from the selection list, they should give a visual indicator of their disabled state, without hover.
list, they > list. They

2021-03-08 21:14 UTC, amalyah commented on _content/components/select.md
> +The Select component consists of an input field containing a downward facing caret icon. Clicking on the caret expands a list of items (below, or above if there is no room below due to the position o
position of the page on screen > position of the component on the screen

relative to the input field > related to the input field (not sure if that's your goal, but I'm not sure what would be relative to the input field otherwise)

2021-03-09 15:26 UTC, Design-Kat commented on _content/components/select.md
> +- Do not remove disabled items from the selection list, they should give a visual indicator of their disabled state, without hover.
Changed it to "list. Disabled items should..."

2021-03-09 15:30 UTC, Design-Kat commented
@amalyah Committed changes.

2021-03-09 18:09 UTC, cskerbo approved these changes

2021-03-11 16:28 UTC, amalyah requested changes
Quick fixes

2021-03-11 16:28 UTC, amalyah commented on _content/components/select.md
> +- Keep the number of list values to a reasonable number to avoid endless scrolling. Alternative components, such as [Input Fields](/components/input-field) and [Search](components/search) (with autoc
/components/search
(I learned that it needs the first slash.)

2021-03-11 16:28 UTC, amalyah commented on _content/components/select.md
> +- Use appropriate field labels, placeholder text, and helper text when possible to assist the user in selecting an appropriate value.
helper text > help text

2021-03-11 16:28 UTC, amalyah commented on _content/components/select.md
> +The Select component consists of an input field containing a downward facing caret icon. Clicking on the caret expands a list of items (below, or above if there is no room below due to the position o
Clicking on the caret expands a list of items... in relation to the input field.
That doesn't make the most sense to me in a sentence. Maybe "related to the input field" instead?

2021-03-12 00:50 UTC, Design-Kat commented on _content/components/select.md
> +The Select component consists of an input field containing a downward facing caret icon. Clicking on the caret expands a list of items (below, or above if there is no room below due to the position o
Yeah that sentence really hasn't worked out has it :D that works. I was going for...the drop down opens and it's right by the input above/below/etc. but it just wasn't working. Oh well.

2021-03-12 14:36 UTC, amalyah approved these changes

2021-03-15 19:39 UTC, dmcalester approved these changes

2021-03-15 19:55 UTC, merged