Astro 1112 create login content
RocketCommunicationsInc/astro-uxds pull request #157
Opened 2021-03-08 22:57 UTC by Design-Kat

Updated Sign in content per Amalya's review on PR #147 

https://rocketcom.atlassian.net/browse/ASTRO-1112

2021-03-08 22:59 UTC, Design-Kat commented
Ready for review by @dmcalester @amalyah @Cheshire89

2021-03-09 20:19 UTC, amalyah requested changes
There are some instances of log in/login that need to be changed to sign in.

2021-03-09 20:19 UTC, amalyah commented on _content/components/sign-in.md
> +git: rux-button
@Design-Kat Will these aspects be changed by devs later?

2021-03-09 20:19 UTC, amalyah commented on _content/components/sign-in.md
> +-  Use a direct, actionable button name, such as Sign In, rather than a more generic “Submit” to post the form.
Sign In > Sign in (sentence case rule)

2021-03-09 20:19 UTC, amalyah commented on _content/components/sign-in.md
> +There are four established types of login workflows.
login workflows > sign in workflows

2021-03-09 20:19 UTC, amalyah commented on _content/components/sign-in.md
> +3. Login with Multi-Factor Authentication (MFA)
Login > Sign in

2021-03-09 20:19 UTC, amalyah commented on _content/components/sign-in.md
> +4. The Sign in can currently be configured to display Sign in with Username or Email Plus Password, and validation.
Sign in with Username > "Sign in with username"
Email Plus Password > "Email plus password"
(sentence case rule)

2021-03-09 20:19 UTC, amalyah commented on _content/components/sign-in.md
> +The login UI elements can be added in 3 possible placement areas.
login UI > sign in UI

2021-03-09 20:19 UTC, amalyah commented on _content/components/sign-in.md
> +* Draws user attention to login process
login process > sign in process

2021-03-09 20:19 UTC, amalyah commented on _content/components/sign-in.md
> +* Draws user attention to login process, without the need for a modal dialog to be placed over an essentially blank page
login process > sign in process

2021-03-09 20:19 UTC, amalyah commented on _content/components/sign-in.md
> +Effective error messaging is important for creating great experiences. Not being able to log into an application is frustrating and blocks users from accomplishing their tasks.
log into > sign into

2021-03-09 20:19 UTC, amalyah commented on _content/components/sign-in.md
> +Validate as much of the user’s data before submission as possible. This real-time validation should happen when the input field loses focus and checks for input errors like invalid characters and emp
login form > sign in form

2021-03-09 20:19 UTC, amalyah commented on _content/components/sign-in.md
> +Always present error states on the login screen, and use inline errors whenever possible when they do not present a security concern.
login screen > sign in screen

2021-03-09 20:19 UTC, amalyah commented on _content/components/sign-in.md
> +If there are server-side errors when the user submits the login form, the page should be reloaded, the password field cleared, and the user returned to the username input field. Use an inline notific
login form > sign in form

2021-03-09 20:19 UTC, amalyah commented on _content/components/sign-in.md
> +* Max # of login attempts reached
login attempts > sign in attempts

2021-03-09 20:19 UTC, amalyah commented on _content/components/sign-in.md
> +Ensure that users can tab through the login form and navigate the page using only a keyboard. Use landmark regions to designate the login region and allow screen readers to skip directly to the input
login form > sign in form
login region > sign in region

2021-03-09 20:19 UTC, amalyah commented on _content/components/sign-in.md
> +![Do: Mask sensitive data, such as passwords](/img/components/component-template-do-1.png "Do: Something")
I suspect the "Do: Something" pieces of the code in the dos and donts are supposed to be edited somehow.

2021-03-09 22:41 UTC, Design-Kat commented on _content/components/sign-in.md
> +![Do: Mask sensitive data, such as passwords](/img/components/component-template-do-1.png "Do: Something")
Ouch. Good catch.

2021-03-09 22:44 UTC, Design-Kat commented on _content/components/sign-in.md
> +git: rux-button
Note: Just committed updates from your comments- I commented these out for now, will update per Duncan's response.

2021-03-10 15:38 UTC, amalyah requested changes
Small changes

2021-03-10 15:38 UTC, amalyah commented on _content/components/sign-in.md
> +![Do: Use clear button labels that describe specific tasks like "Sign in" or "Update password"](/img/components/replaceimage.png "Do: Do: Use clear button labels that describe specific tasks like "Si
Double "Do:" in this quote.
Quotes in text should be changed to single quotes I believe. '
Need to close end of the "Do: ... " statement with a double quote. "

2021-03-10 15:38 UTC, amalyah commented on _content/components/sign-in.md
> +![Don't: Use vague button labels like "Submit" to guide users through authentication flows](/img/components/replaceimage.png "Don't: Use vague button labels like "Submit" to guide users through authe
@Cheshire89 will putting "Submit" in double quotes in this section cause problems for the code?

2021-03-10 16:17 UTC, Design-Kat commented on _content/components/sign-in.md
> +![Don't: Use vague button labels like "Submit" to guide users through authentication flows](/img/components/replaceimage.png "Don't: Use vague button labels like "Submit" to guide users through authe
@amalyah Changed all the double quotes within double quotes to single quotes, will update if need be based on @cheshire89's reply

2021-03-10 20:01 UTC, cskerbo requested changes

2021-03-10 20:01 UTC, cskerbo commented on _content/components/sign-in.md
> +[//]: # git: rux-signin
This is generating a build error as these 3 mapping keys of `[//]` are considered duplicates and need to be unique.

2021-03-10 20:09 UTC, Design-Kat commented on _content/components/sign-in.md
> +[//]: # git: rux-signin
Ah, sorry - I was trying to comment out the code until those pages were completed and could be hooked up, and that is what the internet told me was how to do so in markup. Google fail :) 
Is there something else I can replace it with?

2021-03-10 23:00 UTC, cskerbo commented on _content/components/sign-in.md
> +[//]: # git: rux-signin
You should be able to just delete `[//]:` on each line. If you notice, the `#` successfully commented out the rest of the line.

```
# demo: components-signin--all-signin-variants
# storybook: components-signin--standard-signin
# git: rux-signin
```

2021-03-10 23:03 UTC, cskerbo commented on _content/components/sign-in.md
> +[//]: # git: rux-signin
Deleted my previous statement since we're dealing with Github markdown, you can do this to comment it out:

<!-- demo: components-signin--all-signin-variants -->
<!-- storybook: components-signin--standard-signin -->
<!-- git: rux-signin -->

2021-03-11 16:19 UTC, Design-Kat commented on _content/components/sign-in.md
> +[//]: # git: rux-signin
Committed the update, thank you!

2021-03-11 16:24 UTC, cskerbo approved these changes

2021-03-11 16:37 UTC, amalyah approved these changes

2021-03-15 19:39 UTC, dmcalester approved these changes

2021-03-15 19:56 UTC, merged