ASTRO-1178 Change Everything to Sentence Case
RocketCommunicationsInc/astro-uxds pull request #161
Opened 2021-03-10 21:43 UTC by amalyah

https://rocketcom.atlassian.net/browse/ASTRO-1178

**Sentence Case**
- Changed all label/title references to use sentence case in the documentation.
- Updated compliance documentation accordingly.
- Added compliance entries for pages that didn't already have them (minus SpecA on instruction from Duncan).
- Added the sentence case rule to the Typography page as well.

**Classification Markings Compliance**
- Added missing Classification Marking compliance and specified that this component DOES NOT use sentence case.
- Added other relevant rules as well while I was in there.

**Typos**
- Fixed typos that I came across.
- Added Oxford commas where I found them missing.

2021-03-11 14:51 UTC, Design-Kat commented on _content/_data/compliance.json
> +              "rule": "Text in the overall marking banner shall be as specific as possible to the highest level of classified information contained in that system or view.",
These are inconsistently capitalized. The next rule has Overall Marking Banner capitalized, may want to do a once-over for that.

2021-03-11 15:03 UTC, Design-Kat commented on _content/components/button.md
> +![Don't: Use buttons for actionable controls only](/img/components/button-dont-1.png "Don't: Use buttons for actionable controls only")
Two things on this one: 

1. The Do and Don't are identical.
2. It needs rewording (I know, not technically a part of this ticket, but it WAS edited so I'm mentioning it.) I THINK it's trying to get at DO use buttons to take actions. DON'T use buttons when there is a more appropriate control available ? Alternatively you suggested on Slack that it might be getting at a button needing a function rather than being eye candy, so "DO use buttons for user actions." "DON'T use buttons that don't perform an action." ?

2021-03-11 15:19 UTC, Design-Kat commented on _content/components/radio-button.md
> +- Use Radio Buttons for mutually exclusive choices. If user can make more than one choice, use Checkboxes.
Consider : add an "s" to user, "If user**_s_** can make..."

2021-03-11 15:21 UTC, Design-Kat commented on _content/components/slider.md
> +- To display abstracted values like “Low," Medium,” or “High.”
There's either one too many, or one too few quotation marks in this line. I suspect you mean to have each in quotes separately?

2021-03-11 15:31 UTC, Design-Kat commented on _content/fd-service-ux-design/about-the-fd-designs.md
> +3. **Action Menu** - Rhe action menu is reserved for non-primary actions an operator would execute such as export, print, save, etc&hellip;
"Rhe" should be "The"

2021-03-11 15:50 UTC, Design-Kat commented on _content/ttc-service-ux-design/ttc-command.md
> -1. **Active Alert Hero Number** - Shows number of active alerts at a glance.
In the "About the FD designs" all the numbered items were sentence case after the bold title case text. Either these should be too, or the "About the FD designs" should go back and not capitalize the first word after the dash.

2021-03-11 15:51 UTC, Design-Kat commented on _content/ttc-service-ux-design/ttc-command.md
> +1. **Active Alert Hero Number** - shows number of active alerts at a glance.
Same as above: In the "About the FD designs" all the numbered items were sentence case after the bold title case text. Either these should be too, or the "About the FD designs" should go back and not capitalize the first word after the dash

2021-03-11 15:52 UTC, Design-Kat commented on _content/ttc-service-ux-design/ttc-command.md
>  2. **Pass Indicator** - allows operators to determine if they are in pre-pass, pass or post-pass in relation to the AOS/LOS for the contact.
Same as above: In the "About the FD designs" all the numbered items were sentence case after the bold title case text. Either these should be too, or the "About the FD designs" should go back and not capitalize the first word after the dash

2021-03-11 15:53 UTC, Design-Kat commented on _content/ttc-service-ux-design/ttc-monitor.md
> +1. **Active Alert Hero Number** - shows number of active alerts at a glance.
In the "About the FD designs" all the numbered items were sentence case after the bold title case text. Either these should be too, or the "About the FD designs" should go back and not capitalize the first word after the dash

2021-03-11 15:54 UTC, Design-Kat requested changes
Some minor changes - see comments.

2021-03-11 19:50 UTC, amalyah commented on _content/components/button.md
> +![Don't: Use buttons for actionable controls only](/img/components/button-dont-1.png "Don't: Use buttons for actionable controls only")
@Design-Kat The Do and Don't issue is from over 2 years ago. 0_0

2021-03-11 19:54 UTC, amalyah commented on _content/components/button.md
> +![Don't: Use buttons for actionable controls only](/img/components/button-dont-1.png "Don't: Use buttons for actionable controls only")
I feel like the rewriting for that rule would take more time than I have right now since I think the context is so specific, so I'm going to leave that one off the change list this time around.

2021-03-11 20:06 UTC, amalyah commented on _content/ttc-service-ux-design/ttc-command.md
> -1. **Active Alert Hero Number** - Shows number of active alerts at a glance.
This is something that is inconsistent across the website. We should decide on a standard before making an arbitrary decision just for these pages. Posted the question for discussion in the next Weekly Kickoff meeting agenda. This change would be handled in a different ticket/PR.

2021-03-11 20:06 UTC, amalyah commented on _content/ttc-service-ux-design/ttc-command.md
> +1. **Active Alert Hero Number** - shows number of active alerts at a glance.
This is something that is inconsistent across the website. We should decide on a standard before making an arbitrary decision just for these pages. Posted the question for discussion in the next Weekly Kickoff meeting agenda. This change would be handled in a different ticket/PR.

2021-03-11 20:06 UTC, amalyah commented on _content/ttc-service-ux-design/ttc-command.md
>  2. **Pass Indicator** - allows operators to determine if they are in pre-pass, pass or post-pass in relation to the AOS/LOS for the contact.
This is something that is inconsistent across the website. We should decide on a standard before making an arbitrary decision just for these pages. Posted the question for discussion in the next Weekly Kickoff meeting agenda. This change would be handled in a different ticket/PR.

2021-03-11 20:06 UTC, amalyah commented on _content/ttc-service-ux-design/ttc-monitor.md
> +1. **Active Alert Hero Number** - shows number of active alerts at a glance.
This is something that is inconsistent across the website. We should decide on a standard before making an arbitrary decision just for these pages. Posted the question for discussion in the next Weekly Kickoff meeting agenda. This change would be handled in a different ticket/PR.

2021-03-11 20:11 UTC, amalyah commented
@Cheshire89 It looks the checks all failed for this branch. Is there anything I can do to resolve those issues?

2021-03-11 20:18 UTC, Cheshire89 commented
https://github.com/RocketCommunicationsInc/astro-uxds/pull/161#issuecomment-797017296
@amalyah thank you for letting me know. I'll re run the build

2021-03-15 20:21 UTC, Design-Kat approved these changes

2021-03-15 21:39 UTC, dmcalester approved these changes

2021-03-15 21:58 UTC, dmcalester commented
Hey @amalyah I missed something in my initial review.

Could you change the following:

```
 {
          "name": "Data Visualization",
          "numeral": 2,
          "link": "/patterns/data-visualization/",
          "rules": [
            {
              "numeral": 1,
              "rule": "Data visualizations shall have no more than 8 colors per data set.",
              "status": "new"
            },
            {
              "numeral": 2,
              "rule": "Data visualizations shall use sentence case capitalization for titles, labels, and legends.",
              "status": "new"
            }
        {
```

to

```
 {
          "name": "Data Visualization",
          "numeral": 2,
          "link": "/patterns/data-visualization/",
          "rules": [
            {
              "numeral": 1,
              "rule": "Data visualizations shall have no more than 8 colors per data set.",
              "status": "new"
            },
            {
              "numeral": 2,
              "rule": "Data visualizations shall use sentence case capitalization for titles, labels, and legends.",
              "status": "new"
            }
         ]
},
        {
```

Essentially on like 93 close out the `rules` array. 
Then close the anonymous object for Data Visualization object with a close curly-branch `}`
Finally adding a comma `,`  

I’m not sure the error was on your branch, but it’s the easiest place to fix it right now. I’m happy to jump on a Zoom to walk you through it. JSON is such a bear.

2021-03-15 22:10 UTC, merged

2021-03-16 15:24 UTC, amalyah commented
> Edit: Hang on. Something odd is going on. Need to investigate.
> 
> Skip all this for now.
> 
> Hey @amalyah I missed something in my initial review.
> 
> Could you change the following:
> 
> ```
>  {
>           "name": "Data Visualization",
>           "numeral": 2,
>           "link": "/patterns/data-visualization/",
>           "rules": [
>             {
>               "numeral": 1,
>               "rule": "Data visualizations shall have no more than 8 colors per data set.",
>               "status": "new"
>             },
>             {
>               "numeral": 2,
>               "rule": "Data visualizations shall use sentence case capitalization for titles, labels, and legends.",
>               "status": "new"
>             }
>         {
> ```
> 
> to
> 
> ```
>  {
>           "name": "Data Visualization",
>           "numeral": 2,
>           "link": "/patterns/data-visualization/",
>           "rules": [
>             {
>               "numeral": 1,
>               "rule": "Data visualizations shall have no more than 8 colors per data set.",
>               "status": "new"
>             },
>             {
>               "numeral": 2,
>               "rule": "Data visualizations shall use sentence case capitalization for titles, labels, and legends.",
>               "status": "new"
>             }
>          ]
> },
>         {
> ```
> 
> Essentially on like 93 close out the `rules` array.
> Then close the anonymous object for Data Visualization object with a close curly-branch `}`
> Finally adding a comma `,`
> 
> I’m not sure the error was on your branch, but it’s the easiest place to fix it right now. I’m happy to jump on a Zoom to walk you through it. JSON is such a bear.

Was this taken care of in the draft-2 branch you made above?

2021-03-16 15:25 UTC, dmcalester commented
Yep