Astro 1193 update inputs documentation
RocketCommunicationsInc/astro-uxds pull request #162
Opened 2021-03-11 01:19 UTC by Design-Kat

https://rocketcom.atlassian.net/browse/ASTRO-1193

Added in inputs documentation. 
Note: Numeric input is part of a different ticket (sub branch). Did not add to masked data at this time.

2021-03-11 01:19 UTC, Design-Kat commented
@amalyah Could you take a look at this before I put it up for review with the rest of the team please?

2021-03-11 15:37 UTC, amalyah requested changes
Typo fixes would be needed.

For some of the guidelines, I'm not sure if it would be better to have them ONLY in the form compliance section or on the form AND input compliance sections. Curious about your thoughts.

2021-03-11 15:37 UTC, amalyah commented on _content/_data/compliance.json
> +              "rule": "Input Field labels shall not use placeholder text in place of validation help text.",
Input Field labels > Input Fields

2021-03-11 15:37 UTC, amalyah commented on _content/_data/compliance.json
> +              "rule": "Input Field labels shall not use placeholder text in place of validation help text.",
Also do you mean Validation error text or help text? Right now those are two different things.

2021-03-11 15:37 UTC, amalyah commented on _content/_data/compliance.json
> +              "rule": "Input Field help text shall be aligned to the bottom left of the field.",
This seems like it should be a general form rule instead of an input rule to me.

2021-03-11 15:37 UTC, amalyah commented on _content/_data/compliance.json
> +              "rule": "Input Field labels shall not use placeholder text in place of validation help text.",
This seems like it should be a general form rule instead of an input rule to me.

2021-03-11 15:37 UTC, amalyah commented on _content/_data/compliance.json
> +              "rule": "Input Fields marked as required shall contain an asterisk to the right of the label.",
This seems like it should be a general form rule instead of an input rule to me.

2021-03-11 15:37 UTC, amalyah commented on _content/_data/compliance.json
> +              "rule": "Input Fields marked as optional shall contain the word 'optional' in parenthesis after the label.",
This seems like it should be a general form rule instead of an input rule to me.

2021-03-11 15:37 UTC, amalyah commented on _content/_data/compliance.json
> +              "rule": "Input Fields marked as optional shall contain the word 'optional' in parenthesis after the label.",
parenthesis > parentheses

2021-03-11 15:37 UTC, amalyah commented on _content/components/input-field.md
> +Input Fields allow users to enter freeform text and are often used in forms for data entry.
If we keep this page as a general Input Field, then we still have to include numeric data. If we change it to just Text Input, then this would be true. So I guess it depends on whether you envision numeric inputs as a separate page or not.

2021-03-11 15:37 UTC, amalyah commented on _content/components/input-field.md
> +- When indicating optional fields, add the word _optional_ in parenthesis after the label.
parenthesis > parentheses
(singular vs. plural, more common usage)

2021-03-11 15:37 UTC, amalyah commented on _content/components/input-field.md
> +Text inputs consist of a descriptive, concise label paired with an entry field. Optionally, inputs may include help text, left aligned beneath the input, to assist the user in understanding what kind
visual indicator of whether it's required or optional.

2021-03-11 15:37 UTC, amalyah commented on _content/components/input-field.md
> +Standard states for text inputs include Active (the default, interactive state for a text input), Hover (the user has paused over an active or focussed input), Focus (the field is selected and ready
focussed > focused
it's content > its content

2021-03-11 15:37 UTC, amalyah commented on _content/components/input-field.md
>  An input field can be configured for required input, limited data ranges or specific data formats. See [Form and Input Validation](/patterns/forms-and-validation).
limited data ranges, or specific data formats
(added Oxford comma)

2021-03-11 15:37 UTC, amalyah commented on _content/components/input-field.md
> +- Do not use placeholder text for information that is vital to the user's understanding of the text input. A placeholder will disappear once the input has focus and it should only be used for short,
input has focus and it should  > input has focus, and it should
short, clear and generic instructions > short, clear, and generic instructions

2021-03-11 15:37 UTC, amalyah commented on _content/components/input-field.md
>  An Input field is enabled if it is eligible for interaction, and focused if it is the current target for keystrokes.
eligible for interaction, and focused > eligible for interaction and focused

2021-03-11 15:37 UTC, amalyah commented on _content/patterns/forms-and-validation.md
> +Labels should follow the vertical format of the form. Generally, place labels above their respective fields, and align with [Input Field](/components/input-field) text. Group a label with its field s
fields, and align > fields and align
(no second subject so it's not an independent clause)

2021-03-11 15:38 UTC, amalyah commented on _content/components/input-field.md
> +- When indicating optional fields, add the word _optional_ in parenthesis after the label.
Also the _optional_ styling does not seem to be coming across. Did you mean 'Optional'?

2021-03-11 20:20 UTC, Design-Kat commented on _content/_data/compliance.json
> +              "rule": "Input Field labels shall not use placeholder text in place of validation help text.",
Kind of meant not to use placeholder text instead of help text with validation in I guess? Maybe Validation OR  help text would be a better way of putting it.

2021-03-11 20:22 UTC, Design-Kat commented on _content/_data/compliance.json
> +              "rule": "Input Field labels shall not use placeholder text in place of validation help text.",
> This seems like it should be a general form rule instead of an input rule to me.

Could you be specific o which you're referring to? Github shows two highlights above three comments and it's not clear which your comment belongs to. Line 339?

2021-03-11 20:43 UTC, Design-Kat commented on _content/components/input-field.md
> +Input Fields allow users to enter freeform text and are often used in forms for data entry.
I took it out because text generally includes anything not blacklisted in the character set so I didn't think it needed to be quite that specific, but maybe ... "freeform, alphanumeric text"? I just worry it seems like we're excluding punctuation when you get specific about types of text included.

2021-03-11 21:09 UTC, Design-Kat commented on _content/components/input-field.md
> +- When indicating optional fields, add the word _optional_ in parenthesis after the label.
No, I was trying to make it italics, not sure why it's not displaying, but oh well.

2021-03-11 21:14 UTC, Design-Kat commented on _content/components/input-field.md
>  An input field can be configured for required input, limited data ranges or specific data formats. See [Form and Input Validation](/patterns/forms-and-validation).
I want a script JUST to add Oxford commas for me so I don't have to.

2021-03-11 21:39 UTC, Design-Kat commented on _content/components/input-field.md
> +Input Fields allow users to enter freeform text and are often used in forms for data entry.
@amalyah I created a new compliance section for forms & validation (there wasn't a general forms one) and moved the items into there. I'm torn on whether they should be in both general forms and inputs or not, but lean towards not wanting to overwhelm the user with duplicative statements, so I left it out of Input. Please see the new commit and let me  know if you have any concerns.

2021-03-12 00:43 UTC, Design-Kat commented
@dmcalester @cskerbo @cheshire89 Tag for review, please! :)

2021-03-12 14:43 UTC, amalyah approved these changes

2021-03-12 14:43 UTC, amalyah commented on _content/components/input-field.md
> +- Use required and optional indicators depending on their frequency. e.g. If more fields are optional, only mark required fields.
Nice to have: This seems like something that should be moved to the Forms page instead (or at least duplicated to).

2021-03-12 14:51 UTC, amalyah commented on _content/_data/compliance.json
> +              "rule": "Input Field labels shall not use placeholder text in place of validation help text.",
This one is referring to the line it's attached to: 339.

2021-03-12 23:42 UTC, Design-Kat commented on _content/components/input-field.md
> +- Use required and optional indicators depending on their frequency. e.g. If more fields are optional, only mark required fields.
I duplicated over, and made it a bit more abstracted from the input field so that it could be applied to other controls as needed.

2021-03-17 18:21 UTC, Cheshire89 approved these changes

2021-03-17 21:53 UTC, dmcalester approved these changes

2021-03-18 15:59 UTC, merged