Astro 1189 update numeric inputs documentation
RocketCommunicationsInc/astro-uxds pull request #163
Opened 2021-03-11 01:46 UTC by Design-Kat

https://rocketcom.atlassian.net/browse/ASTRO-1189

Updated for Numeric Inputs.

2021-03-11 01:46 UTC, Design-Kat commented
@amalyah Could you review prior to me tagging the rest of the team please? Thanks! Kat

2021-03-11 15:45 UTC, amalyah requested changes
Only small changes on top of the text input PR version.

2021-03-11 15:45 UTC, amalyah commented on _content/components/input-field.md
> +- When appropriate, use input masking to automatically format a user's entry e.g. When entering a phone number, apply a consistent, recognizable format like (XXX) XXX-XXXX or another similar format.
entry e.g. When > entry. E.g., when

2021-03-11 15:45 UTC, amalyah commented on _content/components/input-field.md
> +Input Fields allow users to enter freeform text. Variations on this field often provide specific data entry formats such as masked data (e.g. passwords or phone numbers), date and time, and numeric d
Ah. This resolves my concern on the text input version of the page.

2021-03-11 15:45 UTC, amalyah commented on _content/components/input-field.md
> +Text inputs consist of a descriptive, concise label paired with an entry field. Optionally, inputs may include help text, left aligned beneath the input, to assist the user in understanding what kind
A text input consists of a... 
(Multiple inputs aren't made out of a single label and field.)

left-aligned

2021-03-11 15:45 UTC, amalyah commented on _content/components/input-field.md
> +Standard states for text inputs include Active (the default, interactive state for a text input), Hover (the user has paused over an active or focussed input), Focus (the field is selected and ready
its content

2021-03-11 15:45 UTC, amalyah commented on _content/components/input-field.md
> +An input field can be configured for required input, limited data ranges or specific data formats. See [Form and Input Validation](/patterns/forms-and-validation). Some variants may allow the user to
control or to jump
(remove comma in front of dependent clause)

2021-03-12 00:38 UTC, Design-Kat commented
@dmcalester @cskerbo @cheshire89 Tag for review, please! :)

2021-03-12 14:48 UTC, amalyah requested changes

2021-03-12 14:48 UTC, amalyah commented on _content/components/input-field.md
> +- Generally, the size of the text input should match the length of the expected input content.
text input > input
(can be true for numeric inputs as well)

2021-03-12 14:48 UTC, amalyah commented on _content/components/input-field.md
> +- When implementing Numeric inputs, utilize browser defaults whenever possible. Define the range and step size within the HTML element when appropriate. Include the range and step size values in the
Mixed capitalization on Numeric inputs.

2021-03-12 14:48 UTC, amalyah commented on _content/components/input-field.md
> +- When appropriate, use input masking to automatically format a user's entry. E.g. When entering a phone number, apply a consistent, recognizable format like (XXX) XXX-XXXX or another similar format.
E.g., when

2021-03-12 14:48 UTC, amalyah commented on _content/components/input-field.md
> +Text input consist of a descriptive, concise label paired with an entry field. Optionally, inputs may include help text, left-aligned beneath the input, to assist the user in understanding what kind
Text input consist > An Input Field consists

2021-03-12 14:48 UTC, amalyah commented on _content/components/input-field.md
> +Standard states for text inputs include Active (the default, interactive state for a text input), Hover (the user has paused over an active or focussed input), Focus (the field is selected and ready
text inputs > input fields

2021-03-12 23:49 UTC, Design-Kat commented on _content/components/input-field.md
> +Standard states for text inputs include Active (the default, interactive state for a text input), Hover (the user has paused over an active or focussed input), Focus (the field is selected and ready
Also capitalized for consistency with earlier paragraphs.

2021-03-12 23:51 UTC, Design-Kat commented
@amalyah updated per your review!

2021-03-15 18:41 UTC, amalyah approved these changes

2021-03-15 20:01 UTC, dmcalester approved these changes

2021-03-15 20:01 UTC, merged