Astro 1174 progress docs update
RocketCommunicationsInc/astro-uxds pull request #164
Opened 2021-03-12 19:58 UTC by amalyah

2021-03-12 21:01 UTC, dmcalester approved these changes

2021-03-12 21:23 UTC, Design-Kat commented on _content/components/toggle.md
> +storybook: components-switch--swittch
Suspect this should be Switch--switch, rather than have two 't's?

2021-03-12 21:49 UTC, Design-Kat commented on _content/ttc-service-ux-design/ttc-command.md
> -1. **Active Alert Hero Number** - Shows number of active alerts at a glance.
Other pages with numbered lists have the first letter after the bolded control capitalized. e.g. Shows, Filters, Expands, Launches.

2021-03-12 21:49 UTC, Design-Kat commented on _content/ttc-service-ux-design/ttc-command.md
>  2. **Pass Indicator** - allows operators to determine if they are in pre-pass, pass or post-pass in relation to the AOS/LOS for the contact.
Other pages with numbered lists have the first letter after the bolded control capitalized.

2021-03-12 21:49 UTC, Design-Kat commented on _content/ttc-service-ux-design/ttc-monitor.md
> -1. **Active Alert Hero Number** - Shows number of active alerts at a glance.
Other pages with numbered lists have the first letter after the bolded control capitalized.

2021-03-12 21:50 UTC, Design-Kat requested changes
A few very minor things yet.

2021-03-15 18:47 UTC, amalyah commented on _content/ttc-service-ux-design/ttc-command.md
> -1. **Active Alert Hero Number** - Shows number of active alerts at a glance.
Will be handled in a separate ticket: https://rocketcom.atlassian.net/browse/ASTRO-1279

2021-03-15 18:47 UTC, amalyah commented on _content/ttc-service-ux-design/ttc-command.md
>  2. **Pass Indicator** - allows operators to determine if they are in pre-pass, pass or post-pass in relation to the AOS/LOS for the contact.
Will be handled in a separate ticket: https://rocketcom.atlassian.net/browse/ASTRO-1279

2021-03-15 18:47 UTC, amalyah commented on _content/ttc-service-ux-design/ttc-monitor.md
> -1. **Active Alert Hero Number** - Shows number of active alerts at a glance.
Will be handled in a separate ticket: https://rocketcom.atlassian.net/browse/ASTRO-1279

2021-03-15 18:48 UTC, amalyah commented
@Design-Kat Updated the Toggle meta-data to fix the typo. Please review again. :)

2021-03-15 20:19 UTC, Design-Kat approved these changes

2021-03-15 20:42 UTC, merged