Astro 1183 help text documentation
RocketCommunicationsInc/astro-uxds pull request #166
Opened 2021-03-17 20:59 UTC by amalyah

https://rocketcom.atlassian.net/browse/ASTRO-1183

Added Help Text Documentation on Astro UXDS website (all form elements, forms and validation, and compliance pages).

2021-03-18 15:20 UTC, Design-Kat commented on _content/_data/compliance.json
> +              "rule": "Help Text shall be left-aligned under the relevant Swittch, regardless of location of the label.",
"Swittch" should be "Switch"

2021-03-18 15:23 UTC, Design-Kat commented on _content/patterns/forms-and-validation.md
> +![Do: Indent Help Text under a Radio Button or Checkbox to align with the list item’s text instead of its icon..](/img/components/help-text-do-2.png "Do: Indent Help Text under a Radio Button or Chec
Was the ".." intentional?

2021-03-18 15:24 UTC, Design-Kat requested changes
A few small spelling/punctuation issues.

2021-03-19 14:28 UTC, Design-Kat approved these changes

2021-03-22 22:28 UTC, dmcalester approved these changes

2021-03-22 22:28 UTC, merged