Astro-1172 Slider Updates to Astro UXDS.
RocketCommunicationsInc/astro-uxds pull request #167
Opened 2021-03-18 20:25 UTC by Design-Kat

Slider documentation updated for UXDS : Note, @amalyah is adding the one small update I have for the Storybook component page to her updates for validation, so that is NOT a part of this PR.

https://rocketcom.atlassian.net/browse/ASTRO-1172

2021-03-18 20:38 UTC, dmcalester commented on _content/components/slider.md
> +A Slider allows users to choose from a range of continuous and discrete values arranged from small to large.
Minor note that in no way precludes approval, but as a range, would it be more accurate to say lowest to highest or perhaps matching the HTML attributes that would be used here of minimum to maximum? Again non-blocker to approval.

2021-03-18 20:41 UTC, dmcalester commented on _content/components/slider.md
> +A Continuous slider is used to select any value along a range, e.g. 0 to 10. A Discrete slider is used to select from a set of pre-defined, specific values pre-defined along the range, e.g. 0, 2, 4,
Another minor nit, but I believe at least in some style guides using e.g. has a comma after the full stop if there are more than one example.

2021-03-18 20:44 UTC, dmcalester commented on _content/components/slider.md
> +##Appearance and Behavior##
Please add a space after the double **##** and remove the **##** from after **Behavior**

2021-03-18 20:45 UTC, dmcalester commented on _content/_data/compliance.json
> +              "figure": "/img/components/input-fields-do-1.png",
This appears to be the wrong image. Is it a place holder?

2021-03-18 20:46 UTC, dmcalester requested changes
Two minor changes and a couple of observations.

2021-03-18 22:37 UTC, Design-Kat commented on _content/_data/compliance.json
> +              "figure": "/img/components/input-fields-do-1.png",
@dmcalester My guess is yes, I don't believe I edited in any images, I'll check it out and fix.

2021-03-19 13:31 UTC, Design-Kat commented on _content/components/slider.md
> +A Slider allows users to choose from a range of continuous and discrete values arranged from small to large.
Updating to "minimum to maximum" to match the HTML attributes.

2021-03-19 13:39 UTC, Design-Kat commented on _content/components/slider.md
> +A Continuous slider is used to select any value along a range, e.g. 0 to 10. A Discrete slider is used to select from a set of pre-defined, specific values pre-defined along the range, e.g. 0, 2, 4,
I did a quick search and most of the guidance (at least on the first page) was more geared towards how to use it rather than the punctuation of it. However, I did see some guidance to avoid "e.g." that I wasn't aware of, so instead of spending more time on it to find the correct answer, I just removed the instances of e.g. on the page :)

2021-03-19 21:09 UTC, amalyah requested changes
See comments

2021-03-19 21:09 UTC, amalyah commented on _content/components/slider.md
> +- Display of start and endpoints, as well as intermediate points (particularly for discrete sliders) is recommended.
slider), is recommended.

2021-03-19 21:09 UTC, amalyah commented on _content/components/slider.md
> +##Appearance and Behavior##
Has this been resolved? I'm still seeing it in the PR.

2021-03-19 21:09 UTC, amalyah commented on _content/components/slider.md
> +A slider comprises of a track, aligned along a vertical or horizontal axis and a visual indicator of where on the axis the current selection exists, and value labels. In Astro, the visual indicator o
A slider comprises of a track aligned along a vertical or horizontal axis, a visual indicator

the visual indicator of the selection value has a selection fill and a thumb indicator.

A label... > The Slider's label is generally above the slider and aligned to the left side of the track. In certain situations, the label may be to the left of the slider and vertically center-aligned to the track instead.

2021-03-19 21:09 UTC, amalyah commented on _content/components/slider.md
> +A Continuous slider is used to select any value along a range, e.g. 0 to 10. A Discrete slider is used to select from a set of pre-defined, specific values pre-defined along the range, e.g. 0, 2, 4,
pre-defined, specific values along the range 
(remove the second instance of the word pre-defined)

2021-03-19 21:09 UTC, amalyah commented on _content/components/slider.md
> +Variations on the slider may include vertical implementations, using tick marks to indicate specific values, additional visual indicators of scale and alternative ways to display the selected value i
visual indicators of scale, and

input-field) or tooltip

2021-03-19 21:11 UTC, amalyah commented on _content/components/slider.md
> +##Appearance and Behavior##
I'm still seeing the issue that Duncan mentioned earlier.
> Please add a space after the double ## and remove the ## from after Behavior

2021-03-19 21:27 UTC, Design-Kat commented on _content/components/slider.md
> +##Appearance and Behavior##
Yeah, I forgot to "push to origin" so it was committed locally, but not pushed to the site. Oops.

2021-03-19 21:29 UTC, Design-Kat commented on _content/_data/compliance.json
> +              "figure": "/img/components/input-fields-do-1.png",
Already done- I forgot to hit "push to origin" so it only committed locally, oops :)

2021-03-19 21:30 UTC, Design-Kat commented on _content/components/slider.md
> +- It is not recommended to use a slider when a very large value range exists. E.g. A range of 1,000, or fractional increments such as 4.35, may be too specific to use a slider. Consider using a numer
Sorry, this was already removed, I had changed it to "exists. A range of" and removed the e.g. completely. Just forgot to push to origin on the site.

2021-03-19 21:39 UTC, Design-Kat commented
@amalyah Sorry about that- I actually pushed to origin this time instead of just committing locally - it really  helps to do that final step! 😄 Completed updating per your review.

2021-03-22 15:31 UTC, nortonprojects approved these changes

2021-03-23 19:44 UTC, amalyah requested changes
Quick change request

2021-03-23 19:44 UTC, amalyah commented on _content/components/slider.md
> -To learn more about adding Help Text to Sliders, see the [Forms and Validation](/patterns/forms-and-validation) guidance.
We need to keep this statement. Could you add it back in at the bottom of the Appearance and Behavior section?

2021-03-24 14:29 UTC, Design-Kat commented on _content/components/slider.md
> -To learn more about adding Help Text to Sliders, see the [Forms and Validation](/patterns/forms-and-validation) guidance.
Sorry, I don't recall removing that statement, added back.

2021-03-24 14:30 UTC, Design-Kat commented on _content/components/slider.md
> -To learn more about adding Help Text to Sliders, see the [Forms and Validation](/patterns/forms-and-validation) guidance.
Fixed- see latest commit please.

2021-03-24 15:26 UTC, dmcalester approved these changes

2021-03-24 17:43 UTC, amalyah approved these changes

2021-03-24 17:46 UTC, Design-Kat commented
@dmcalester @Cheshire89 @nortonprojects is anyone available to to merge this pull request? It looks like it has all the needed approvals now. 

Thanks much!

2021-03-24 18:24 UTC, merged