Astro 1198 Update Validation Documentation
RocketCommunicationsInc/astro-uxds pull request #168
Opened 2021-03-18 21:31 UTC by amalyah

https://rocketcom.atlassian.net/browse/ASTRO-1198
Builds off of the Help Text documentation changes.

Side task: Quick update to Slider documentation for clarification.

2021-03-19 20:57 UTC, Design-Kat approved these changes

2021-03-23 15:40 UTC, Cheshire89 requested changes
refer to comments

2021-03-23 15:40 UTC, Cheshire89 commented on _content/patterns/forms-and-validation.md
> +![Numeric Range - Input must be a number within a specific range. Non-numeric characters and out-of-range values are indicated with a warning icon and instructional text.](/img/patterns/val-numeric-r
@amalyah  In html there is no such thing as numeric range  there is either numeric input or range input. Both however accept min and max attributes (range requires them) to set limits on acceptable values. Given that this paragraph is a bit miss leading

2021-03-23 15:47 UTC, amalyah commented on _content/patterns/forms-and-validation.md
> +![Numeric Range - Input must be a number within a specific range. Non-numeric characters and out-of-range values are indicated with a warning icon and instructional text.](/img/patterns/val-numeric-r
FYI @Design-Kat

2021-03-23 15:50 UTC, amalyah commented on _content/patterns/forms-and-validation.md
> +![Numeric Range - Input must be a number within a specific range. Non-numeric characters and out-of-range values are indicated with a warning icon and instructional text.](/img/patterns/val-numeric-r
I only updated a bit of the wording in this statement and I'm not sure who originally wrote the rules, but I will try to disentangle this one for you.

2021-03-23 16:04 UTC, Cheshire89 approved these changes

2021-03-23 17:30 UTC, dmcalester approved these changes

2021-03-23 17:30 UTC, merged