Astro 1284 update image assets for astro uxds
RocketCommunicationsInc/astro-uxds pull request #172
Opened 2021-03-25 03:13 UTC by Design-Kat

https://rocketcom.atlassian.net/browse/ASTRO-1284

Should be all the currently updated Image Assets for PI 2021-1.

@amalyah please review when you get a chance to ensure I've included all the correct images. Not included: Any image from service-specific folders, and images blocked out as still needing update/links to Astro 6.

2021-03-25 15:28 UTC, Design-Kat commented
Note: All images should have been updated that need updating at this point (previously Sign-in was still being completed).

2021-03-25 15:38 UTC, dmcalester commented on _content/components/sign-in.md
> +[Example of a full-page, simple sign in screen](/img/components/signin-simple-full.png "Example of a full-page, simple sign in screen")
Please add an exclamation point (!) here to get the image to render e.g. 

```
![Example of a full-page, simple sign in screen](/img/components/signin-simple-full.png "Example of a full-page, simple sign in screen")
```

2021-03-25 15:38 UTC, dmcalester commented on _content/components/sign-in.md
> +[Example of a sign in screen hosted within a modal dialog](/img/components/signin-dialog-simple.png "Example of a sign in screen hosted within a modal dialog")
Exclamation point

2021-03-25 15:39 UTC, dmcalester commented on _content/components/sign-in.md
> +[Example of Single Sign-on hosted within a modal dialog](/img/components/signin-dialog-sso.png "Example of Single Sign-on hosted within a modal dialog")
Please add exclamation point before the opening bracket

2021-03-25 15:40 UTC, dmcalester commented on _content/components/sign-in.md
> +[Example of a sign in screen hosted within a modal dialog](/img/components/signin-dialog-simple.png "Example of a sign in screen hosted within a modal dialog")
Please add exclamation point before the opening bracket

2021-03-25 15:40 UTC, dmcalester commented on _content/components/sign-in.md
> +[Example of a sign in screen located within a sidebar](/img/components/signin-sidebar-simple-full.png "Example of a sign in screen located within a sidebar")
Please add exclamation point before the opening bracket

2021-03-25 15:40 UTC, dmcalester commented on _content/components/sign-in.md
> +[Example of a full-page sign in screen](/img/components/signin-simple-full.png "Example of a full-page sign in screen")
Please add exclamation point before the opening bracket

2021-03-25 15:40 UTC, dmcalester commented on _content/components/sign-in.md
> +[Example of a full-page account lock out (access denied) screen](/img/components/signin-accessdenied-full.png "Example of a full-page account lock out (access denied) screen")
Please add exclamation point before the opening bracket

2021-03-25 15:43 UTC, dmcalester requested changes
See inline comments all reference adding a missing exclamation point to some images so they render. Otherwise approved.

2021-03-25 15:48 UTC, Design-Kat commented
> See inline comments all reference adding a missing exclamation point to some images so they render. Otherwise approved.

Should be all in now, thank you, @dmcalester !

2021-03-25 16:25 UTC, amalyah requested changes
- Design Guidelines/Grid images look blurry. If we add them to the re-export, could that be fixed?
- Gradual Visualization Palette image updates needs to be removes or they need to be re-exported without the NEEDS TO BE LINKED text and opacity cover over them.
- Help text do and dont images aren't showing up on the Forms and Validation page.
- New checkbox images aren't showing up on the checkbox page
- Sign In large images aren't showing up on the Sign In page.
- Some images changed size slightly, others by a lot. Not sure if that's an issue or not.

2021-03-25 17:04 UTC, Design-Kat commented
@amalyah 

* Design Guidelines/Grid images look blurry: This is because it’s a bitmap, the original needs to be found and added- maybe that should be a separate ticket/bug? 
*  Gradual Visualization Palette: I re-exported them without the opacity over it.
* Fixed some folder and image name issues on Checkbox, sign in, and forms & validation that should fix the issues you saw with images showing up.

2021-03-25 17:13 UTC, dmcalester requested changes
The full screen images for modal, sidebar and full page are mis-rendering @nortonprojects could you lend a hand?

2021-03-25 17:28 UTC, amalyah requested changes
Only thing that I see wrong now is the Sign In images that Duncan already mentioned.

2021-03-25 19:01 UTC, amalyah approved these changes
Styling issue: Numbered bullet points do not keep the numbers that Kat entered in the code.

2021-03-25 19:05 UTC, dmcalester approved these changes
Approved for image update.

2021-03-25 19:21 UTC, amalyah approved these changes
Numbering issue is fixed now too.

2021-03-25 19:30 UTC, nortonprojects commented
> Numbering issue is fixed now too.

Touching up the sizing, and I'll clean up the git history a bit

2021-03-25 19:45 UTC, dmcalester approved these changes

2021-03-25 19:46 UTC, cskerbo approved these changes

2021-03-25 21:10 UTC, amalyah approved these changes

2021-03-26 13:23 UTC, Design-Kat commented
@dmcalester @Cheshire89 it looks like this has all the approvals required as of yesterday, could this be merged so the ticket can be closed?

2021-03-26 15:45 UTC, merged