Updated fonts sizes in design guidance
RocketCommunicationsInc/astro-uxds pull request #176
Opened 2021-05-03 23:44 UTC by dmcalester

Font sizes were in design guidelines were not updated to reflect Astro 5/KM1.2 changes

2021-05-04 14:49 UTC, Full-lifey commented on _content/design-guidelines/typography.md
> +| Heading Level 3     | Medium  | `<h3>` | 1.25 | 20  | `.h3` |
Can we have something more specific in weights? Normal is a CSS value, but medium is not. Can we change these to specific values that developers can use?

2021-05-04 15:13 UTC, Full-lifey requested changes
Thanks for the edits. Just need to move the number on line 37

2021-05-04 15:13 UTC, Full-lifey commented on _content/design-guidelines/typography.md
> +| Extra small (400) | Normal | 0.65  | 10  | `.xs` |
This 400 needs to shift into the next column.

2021-05-04 15:25 UTC, Full-lifey approved these changes

2021-05-05 13:49 UTC, amalyah commented
@dmcalester Is this PR attached to a ticket?

2021-05-05 13:52 UTC, amalyah commented
Not directly related to this PR's changes, but is the size of the code text intentional? It's a lot bigger compared to our normal text size on Astro UXDS.

2021-05-05 14:00 UTC, amalyah commented
Do we want to include letter spacing in this table? In the design files we have specific letter spacing for each one (as mandated by KM in many instances).

2021-05-05 14:03 UTC, amalyah commented on _content/design-guidelines/typography.md
> +| Extra small | Normal (400) | 0.65  | 10  | `.xs` |
What do we use this font size for? I don't have it in the design files which means we probably have an inconsistency.

2021-05-05 15:00 UTC, dmcalester commented on _content/design-guidelines/typography.md
> +| Extra small | Normal (400) | 0.65  | 10  | `.xs` |
It’s likely not used, just created for utility.

2021-05-05 15:00 UTC, merged

2021-05-05 15:02 UTC, dmcalester commented
> Do we want to include letter spacing in this table? In the design files we have specific letter spacing for each one (as mandated by KM in many instances).

Will create a ticket, this was more of an immediate need to fix. I think that kind of guidance is worth a go-back, it’s incredibly specific and ties the hands of designers.