Updating to Astro 5.1
RocketCommunicationsInc/astro-uxds pull request #177
Opened 2021-05-05 15:11 UTC by dmcalester

- New guidance on Sign In patterns
- Updated guidance on Form Fields and validation aligning with Kobayashi Maru 1.2 guidance
- Fixed incorrect font size guidance

2021-05-05 16:13 UTC, dmcalester commented
Preparing to publish 5.1

2021-05-05 16:49 UTC, amalyah commented
The "Propose a change or fix to this page" link appears to be broken throughout the site.

2021-05-05 16:51 UTC, dmcalester commented
> The "Propose a change or fix to this page" link appears to be broken throughout the site.

That link is dynamically generated and linked to the git branch. Unfortunately as deploy previews are ephemeral and don’t have a branch those links won’t work.

2021-05-05 16:59 UTC, amalyah commented
Design Process images are still blurry. (Known issue I think, but thought I'd mention it in case it wasn't.)

2021-05-05 17:41 UTC, amalyah commented
Note for all GRM/TT&C pages: #contentBottom links no longer works and Bitbucket link at the bottom is no longer accurate.

2021-05-05 18:19 UTC, amalyah commented
Image issue: _content/img/patterns/val-required-input.png

Second input (the invalid one) needs to have the text content changed from a value back to placeholder text so that the context of the field being invalid because it's a required field makes sense.

2021-05-05 18:19 UTC, amalyah requested changes
See comments.

2021-05-05 18:53 UTC, dmcalester commented on _content/components/switch.md
> +storybook: components-switch--switch
Known issue, it shouldn’t be an issue when it leaves preview

2021-05-05 18:55 UTC, dmcalester commented on netlify.toml
> +[[redirects]]
Weird it’s in `master`

2021-05-05 19:31 UTC, dmcalester commented on _content/components/sign-in.md
> +![Example of a full-page, simple sign in screen](/img/components/signin-simple-full.png "Example of a full-page, simple sign in screen")
Deferred

2021-05-05 19:35 UTC, dmcalester commented on _content/design-guidelines/theme.md
>  ## Implementation
Deferred

2021-05-05 19:41 UTC, dmcalester commented on _content/components/__template.md
> +demo: components-buttons--all-button-variants
It’s an area for us to test. It doesn’t get published.

2021-05-06 13:44 UTC, amalyah commented on _content/getting-started/designers.md
> +[Astro Light Library](https://github.com/RocketCommunicationsInc/astro-design-resources/raw/master/Sketch/Astro%20Dark%20Library.sketch)
@dmcalester This still appears to be an issue. Should we address it or defer it?

2021-05-06 13:45 UTC, amalyah commented on _content/getting-started/_readme.md
> +::: caution When implementing Astro Space UX Design System users should consult with their organization's IT/Security departments and adapt these patterns to suit the needs of their organization’s be
@dmcalester This is still an issue. Should we address it or defer?

2021-05-06 13:51 UTC, amalyah commented on _content/components/checkbox.md
> +Don’t use a Checkbox to initiate an action. Instead, use an [Action Button](/components/button) or a [Switch Button](/components/switch)
Is the component technically a Switch or a Switch Button? (I thought it was Switch, but I may be incorrect).

2021-05-06 13:51 UTC, amalyah commented on _content/fd-service-ux-design/about-the-fd-designs.md
> +The [Global Status Bar](../../components/global-status-bar) of the FDS app contains a single sign in, high level navigation [tabs](../../components/tabs) to switch between tools, a [clock](../../comp
@dmcalester This is still an issue. Should this be addressed or deferred?

2021-05-06 13:53 UTC, amalyah requested changes
Still pending some resolution or decision on deferment on issues found in last review related to the following pages:
_content/getting-started/designers.md
_content/getting-started/_readme.md
_content/fd-service-ux-design/about-the-fd-designs.md
_content/components/checkbox.md

2021-05-11 20:12 UTC, amalyah commented on _content/getting-started/_readme.md
> +::: caution When implementing Astro Space UX Design System users should consult with their organization's IT/Security departments and adapt these patterns to suit the needs of their organization’s be
@dmcalester Agreed that this should be addressed before merge since it looks actively broken.

2021-05-11 20:21 UTC, amalyah requested changes
Approved pending fix to caution note in the Getting Started Read Me page preview.

2021-05-12 16:25 UTC, dmcalester commented
@Cheshire89 @amalyah @cskerbo @Full-lifey Amalya has done a review. Just looking for anything show-stopping at this point.

2021-05-12 17:16 UTC, amalyah approved these changes

2021-05-13 14:40 UTC, merged