Astro 1397 add material themes
RocketCommunicationsInc/astro-uxds pull request #180
Opened 2021-05-07 23:21 UTC by Full-lifey

Add material themes to download page and how to for developers.

@dmcalester Should we add the links for the material deployments somewhere for users to view?

2021-05-10 16:13 UTC, amalyah commented
@Full-lifey Looks like the branch is out-of-date with the base branch. Could you update that before we do our reviews?

2021-05-10 16:16 UTC, Full-lifey commented
Tagging as Work In Progress until I can format code blocks better.

2021-05-10 21:34 UTC, Full-lifey reviewed
NOTE: The change of the code element sizing affected 1 line in the Patterns>Forms and Validation.

It was a small inline piece of code and still conveys that it's code so I have not updated it. If I should, please let me know.

2021-05-11 20:45 UTC, amalyah commented on _content/getting-started/developers.md
> +We also have Material Design themes using Astro styling. These files include everything needed to build an Astro Application using both Astro Components and/or Material Design Components
Material Design Components. (add period at the end)

2021-05-11 20:47 UTC, amalyah commented on _content/getting-started/developers.md
> +    - Dark Theme (Default) - <div class="code-block">`<link rel="stylesheet" href="https://gitcdn.link/repo/RocketCommunicationsInc/astro-material-themes/main/dark/dist/darkTheme.css" />`</div>
I'd suggest removing the hyphen after Dark Theme (Default) and Light Theme since the code block styling and the lack of whitespace between the text and the code block already provides enough differentiation and grouping cues.

2021-05-11 21:06 UTC, Full-lifey commented on css/app.css
> +.navigation{position:relative;color:#fff;overflow-y:auto;scrollbar-color:var(--nav-scrollbar-thumb-color) var(--nav-scrollbar-track-color);scrollbar-width:thin;padding-bottom:2rem;transition:scrollba
Correct, these are output files from the build process. The one-line files take up less space and therefore make the application quicker (admittedly by a small %). 

After updating the styling for the code blocks I needed to do a build and this is the output. Usually the build outputs are not committed to the repository causing this to be a non-issue.

2021-05-11 21:06 UTC, Full-lifey commented on _content/getting-started/developers.md
> +## Astro for Material Design
Fixed

2021-05-11 21:07 UTC, Full-lifey commented on _content/getting-started/developers.md
> +We also have Material Design themes using Astro styling. These files include everything needed to build an Astro Application using both Astro Components and/or Material Design Components
Fixed

2021-05-11 21:07 UTC, Full-lifey commented on _content/getting-started/developers.md
> +- Download CSS Files Directly - Each can be found in our [downloads section](/downloads)
Done

2021-05-11 22:04 UTC, amalyah requested changes
Just one period to go and then approved.

2021-05-11 22:04 UTC, amalyah commented on _content/getting-started/developers.md
> +- Via CDN - Simply add the one line of code to your HTML and get the newest version of Astro for Material Design
Missing period at the end of sentence.

2021-05-11 22:05 UTC, Full-lifey commented on _content/getting-started/developers.md
> +- Via CDN - Simply add the one line of code to your HTML and get the newest version of Astro for Material Design
Dang! I thought I got that one. Thanks

2021-05-11 22:15 UTC, Full-lifey commented on _content/getting-started/developers.md
> +- Via CDN - Simply add the one line of code to your HTML and get the newest version of Astro for Material Design
It has been added

2021-05-12 13:57 UTC, amalyah approved these changes

2021-05-13 15:05 UTC, cskerbo approved these changes

2021-05-13 17:40 UTC, Cheshire89 approved these changes

2021-05-13 17:53 UTC, merged