Astro 1450 application state
RocketCommunicationsInc/astro-uxds pull request #186
Opened 2021-05-25 20:53 UTC by micahjones13

Added Application State page w/ compliance section, added app state to nav

2021-05-25 20:55 UTC, micahjones13 commented on _content/_data/compliance.json
> +              "status": "new"
Assuming this status would be new, but please let me know otherwise.

2021-05-25 20:55 UTC, micahjones13 commented on _content/components/application-state.md
> +# demo: components-application-state--application-state
Commented out due to lack of a story book demo for app state just yet

2021-05-25 20:56 UTC, micahjones13 commented on _content/components/application-state.md
> +- The default color for the background rectangle uses the --colorTertiaryDarken4 variable, but can be changed to any of the Tag-approved colors in the Astro palette when more user attention to the co
I left all references to --colorTeriaryDarken4 as is, but was thinking they might look better bolded or in a code snippet, let me know what y'all think

2021-05-25 21:43 UTC, Full-lifey approved these changes

2021-05-25 21:43 UTC, Full-lifey commented on _content/components/application-state.md
> +- The default color for the background rectangle uses the --colorTertiaryDarken4 variable, but can be changed to any of the Tag-approved colors in the Astro palette when more user attention to the co
I agree it would probably look better as an inline code snippet but I don't think it's a big deal. 

Let's see what design says.

2021-05-26 14:26 UTC, amalyah commented on _content/components/application-state.md
> +- The default color for the background rectangle uses the --colorTertiaryDarken4 variable, but can be changed to any of the Tag-approved colors in the Astro palette when more user attention to the co
I think the code styling would be good for the variable names.

2021-05-26 14:36 UTC, amalyah requested changes
Only small changes required. Nice job!

2021-05-26 14:36 UTC, amalyah commented on _content/components/application-state.md
> +# demo: components-application-state--application-state
Is there another ticket created for the Storybook component and to uncomment out this one?

2021-05-26 14:36 UTC, amalyah commented on _content/components/application-state.md
> +- The default color for the background rectangle uses the --colorTertiaryDarken4 variable, but can be changed to any of the Tag-approved colors in the Astro palette when more user attention to the co
Code styling sounds good to me.

2021-05-26 14:36 UTC, amalyah commented on _content/components/application-state.md
> +![Don't: Place the indicator below the application menu.](/img/components/app-state-dont-1.png "Don't: Something")
Missing content in "Don't: Something" area.

2021-05-26 14:36 UTC, amalyah commented on _content/components/application-state.md
> +![Do:  Show all relevant state names if more than one application state is ongoing at the time.](/img/components/app-state-do-2.png "Do:  Show all relevant state names if more than one application st
Extra space between Do: and rule should be removed.

2021-05-26 14:36 UTC, amalyah commented on _content/components/application-state.md
> +![Don't: Allow other elements of the user interface besides the application menu to obscure the application state.](/img/components/app-state-dont-2.png "Allow other elements of the user interface be
Missing "Don't:" in the quotation section here.

2021-05-26 14:36 UTC, amalyah commented on _content/components/application-state.md
> +![Do: Use short names to avoid overcrowding of the Global Status Bar.](/img/components/app-state-do-3.png "Use short names to avoid overcrowding of the Global Status Bar.")
Missing "Do:" in the quotation section here.

2021-05-26 14:36 UTC, amalyah commented on _content/components/application-state.md
> +![Do: Use the application menu to enable state switching when necessary.](/img/components/app-state-do-4.png "Use the application menu to enable state switching when necessary.")
Missing "Do:" in the quotation section here.

2021-05-26 14:36 UTC, amalyah commented on _content/components/application-state.md
> +![Do: Change text color --colorTertiaryDarken4 if the background color makes the original text color hard to read.](/img/components/app-state-do-5.png "Change text color --colorTertiaryDarken4 if the
Missing "Do:" in the quotation section here.

2021-05-26 14:37 UTC, amalyah commented
@micahjones13 Could you add the link to the relevant Jira Ticket in the Branch description?

2021-05-26 15:57 UTC, micahjones13 commented on _content/components/application-state.md
> +# demo: components-application-state--application-state
I just looked and didn't find one. That may be a q for @dmcalester

2021-05-26 16:00 UTC, micahjones13 commented on _content/components/application-state.md
> +![Do: Change text color ```--colorTertiaryDarken4``` if the background color makes the original text color hard to read.](/img/components/app-state-do-5.png "Do: Change text color ```--colorTertiaryD
The code styling on the variable here is different from all of the ones above due to the HTML element it's in. Let me know if you want this changed and I can look into it @amalyah

2021-05-26 16:33 UTC, amalyah commented on _content/components/application-state.md
> +![Do: Change text color ```--colorTertiaryDarken4``` if the background color makes the original text color hard to read.](/img/components/app-state-do-5.png "Do: Change text color ```--colorTertiaryD
I think it would make sense to use the same styling for code variables regardless of where the text is if it's not too much trouble. If it is too much work, then it is fine as is, but the alt tag portion of the text does not need the ''' portions since it renders the characters and not the styling in an alt tag.

2021-05-26 16:42 UTC, amalyah approved these changes

2021-05-26 16:50 UTC, micahjones13 commented on _content/components/application-state.md
> +![Do: Change text color ```--colorTertiaryDarken4``` if the background color makes the original text color hard to read.](/img/components/app-state-do-5.png "Do: Change text color ```--colorTertiaryD
Oh good catch on the alt tag. Will try getting the styling uniform.

2021-05-26 20:55 UTC, micahjones13 commented
The variable inside of the Do section is now styled the same as the rest.

2021-05-27 13:41 UTC, amalyah requested changes
Itty bitty change request for a missing word and questions about span code in alt tags.

2021-05-27 15:29 UTC, micahjones13 commented on _content/components/application-state.md
> +![Do: Change text color <span style="color:#fff;background-color:#182635;font-family:monospace;padding:0 0.25rem;">--colorTertiaryDarken4</span> if the background color makes the original text color
I checked the alt text in firefox and edge as well, and it looks like it does in chrome. I also ran the custom span section through a screen reader and it read it fine.

2021-05-27 15:29 UTC, micahjones13 commented on _content/components/application-state.md
> +![Do: Change text color <span style="color:#fff;background-color:#182635;font-family:monospace;padding:0 0.25rem;">--colorTertiaryDarken4</span> if the background color makes the original text color
Thank you!

2021-05-27 16:34 UTC, amalyah requested changes
One last "to" to add.

2021-05-27 16:34 UTC, amalyah commented on _content/components/application-state.md
> +![Do: Change text color to <span style="color:#fff;background-color:#182635;font-family:monospace;padding:0 0.25rem;">--colorTertiaryDarken4</span> if the background color makes the original text col
The same change (add "to") needs to happen in the caption section of Do-5 as well.

2021-05-27 16:56 UTC, micahjones13 commented on _content/components/application-state.md
> +![Do: Change text color to <span style="color:#fff;background-color:#182635;font-family:monospace;padding:0 0.25rem;">--colorTertiaryDarken4</span> if the background color makes the original text col
don't know how I missed that one, thanks. Fixed now

2021-05-27 16:57 UTC, amalyah approved these changes

2021-05-27 17:10 UTC, NicDominguez approved these changes
Clear and well organized. Great job!

2021-05-27 17:28 UTC, merged