docs: added dep notes to sketch files, updated figma section
RocketCommunicationsInc/astro-uxds pull request #207
Opened 2021-09-02 20:37 UTC by micahjones13

Adds deprecation notes to sketch files, updates the figma section to include the Astro UXDS Figma link.

Jira: https://rocketcom.atlassian.net/browse/ASTRO-1528

2021-09-02 20:37 UTC, micahjones13 commented on _content/getting-started/designers.md
> +[Astro UXDS Figma Page](https://www.figma.com/community/file/1014254163928270411)
Let me know if there are any other links that need to be added here

2021-09-09 20:33 UTC, amalyah requested changes

2021-09-09 20:33 UTC, amalyah commented on _content/downloads.md
>  - Astro Sketch Dark Library ([Git Repository](https://github.com/RocketCommunicationsInc/astro-design-resources/tree/master/Sketch))
We should add the link to the Figma page in this list as well.

2021-09-09 20:33 UTC, amalyah commented on _content/getting-started/designers.md
> +[Astro UXDS Figma Page](https://www.figma.com/community/file/1014254163928270411)
This is all we need for the links for right now. In the future we will add the Icons library, but Duncan hasn't published that one yet.

2021-09-09 20:33 UTC, amalyah commented on _content/getting-started/designers.md
>  To download the Design starter kit, navigate to Astro Design Resources [Git Repository](https://github.com/RocketCommunicationsInc/astro-design-resources)
Is there any way in the downloadable design resources that we could add a note in a readme or something that Sketch is deprecated and to include the Figma link there?

2021-09-09 20:33 UTC, amalyah commented on _content/getting-started/designers.md
>  ### Sketch Installation and Use
To make it clear which instructions are related to Sketch, can we make a separate Sketch section with all these related sections under it?

 Example:
 ### (h3) Sketch
 (the deprecation note can go below this heading)
 #### (h4) Sketch Installation and Use
 #### (h4) How to use Astro Sketch libraries
Etc.

If we don't have an h4 equivalent, then we should bump the h3 ones up to h2 throughout the page so that we can put the extra sketch info in as h3s (###).

If the heading size changes are in another ticket, could you tell me what the Jira link is for that one?

2021-09-09 20:59 UTC, micahjones13 commented on _content/getting-started/designers.md
>  To download the Design starter kit, navigate to Astro Design Resources [Git Repository](https://github.com/RocketCommunicationsInc/astro-design-resources)
Definitely! To make sure, you're talking about [this repo?](https://github.com/RocketCommunicationsInc/astro-design-resources)

2021-09-09 21:02 UTC, amalyah commented on _content/getting-started/designers.md
>  To download the Design starter kit, navigate to Astro Design Resources [Git Repository](https://github.com/RocketCommunicationsInc/astro-design-resources)
Yup. Looks like we should add the deprecation note about sketch to the readme file as well.

2021-09-09 21:10 UTC, micahjones13 commented on _content/getting-started/designers.md
>  To download the Design starter kit, navigate to Astro Design Resources [Git Repository](https://github.com/RocketCommunicationsInc/astro-design-resources)
Ticket created https://rocketcom.atlassian.net/browse/ASTRO-1931

2021-09-09 21:15 UTC, micahjones13 commented on _content/getting-started/designers.md
>  To download the Design starter kit, navigate to Astro Design Resources [Git Repository](https://github.com/RocketCommunicationsInc/astro-design-resources)
Also added Sketch deprecation and figma link note to the getting-started readme

2021-09-10 15:03 UTC, amalyah requested changes

2021-09-10 15:03 UTC, amalyah commented on _content/getting-started/designers.md
> +## How to Use Astro Icon Library
This is Sketch-specific, so it can be a ###

2021-09-10 15:03 UTC, amalyah commented on _content/getting-started/designers.md
> +## How to use Astro color swatches
This is Sketch-specific so it can be a ###

2021-09-10 15:03 UTC, amalyah commented on _content/getting-started/designers.md
> +## Updating/Syncing
This is Sketch-specific so it can be a ###

2021-09-10 15:03 UTC, amalyah commented on _content/getting-started/designers.md
> +## Importing Sketch Files into Adobe XD
This is Sketch-specific so it can be a ###

2021-09-10 20:03 UTC, amalyah approved these changes

2021-09-13 17:12 UTC, NicDominguez approved these changes
Looks good. This will be really helpful to clarify what we are doing to our users.

2021-09-13 17:14 UTC, merged