updated "airmen" to "Airmen and Gaurdians"
RocketCommunicationsInc/astro-uxds pull request #210
Opened 2021-09-21 19:59 UTC by Full-lifey

2021-09-21 20:23 UTC, micahjones13 approved these changes

2021-09-21 21:31 UTC, NicDominguez approved these changes

2021-09-22 18:29 UTC, amalyah requested changes

2021-09-22 18:29 UTC, amalyah commented on _content/index.md
> +The Astro Space UX Design System enables development teams to build rich space app experiences and custom applications with established interaction patterns and best practices. Using Astro to design
Gaurdians > Guardians

2021-09-22 18:56 UTC, micahjones13 commented on _content/index.md
> +The Astro Space UX Design System enables development teams to build rich space app experiences and custom applications with established interaction patterns and best practices. Using Astro to design
Leave it to 3 different devs to not know how to spell guardians lol

2021-09-22 23:49 UTC, Full-lifey commented on _content/index.md
> +The Astro Space UX Design System enables development teams to build rich space app experiences and custom applications with established interaction patterns and best practices. Using Astro to design
In need of facepalm emoji

2021-09-23 14:41 UTC, amalyah approved these changes

2021-09-23 16:30 UTC, merged