WIP: Astro-377/671 - Classification Marking content
RocketCommunicationsInc/astro-uxds pull request #85
Opened 2020-09-18 16:24 UTC by im-cr

## Subtask of Astro 377 - https://rocketcom.atlassian.net/browse/ASTRO-671

**Acceptance Criteria**
- AstroUXDS.com/components/classification-markings is live on the draft site
- No broken links
- All styles and necessary illustrations
- Renders correctly in all Astro targeted browsers including mobile

2020-09-18 16:27 UTC, im-cr commented
@dmcalester Task specifies placing classification markings under components dir but another comment mentioned placing within the 'patterns' dir.

2020-09-18 20:34 UTC, dmcalester requested changes

2020-09-18 20:34 UTC, dmcalester commented on _content/components/classification-markings.md
> +| Top Secret//SCI<br>(Sensitive Compartmented Information) 	| #FCE83A   	| 252, 232, 58 	| --classificationTopSecretSCI 	| --colorBlack 	|
Add color swatches similar to how colors are shown in https://deploy-preview-85--astrouxds.netlify.app/design-guidelines/color/

2020-09-18 20:34 UTC, dmcalester commented on _content/components/classification-markings.md
> +
Add the sample component from Storybook

2020-09-18 20:34 UTC, dmcalester commented on _content/components/classification-markings.md
> +| Top Secret                                               	| #FF8C00   	| 255, 140, 0  	| --classificationTopSecret    	| --colorBlack 	|
User lower case for hex values

2020-09-18 20:34 UTC, dmcalester commented on _content/components/classification-markings.md
> +| Unclassified (UUI)                                       	| #007A33   	| 0, 122, 51   	| --classificationUnclassified 	| --colorWhite 	|
- Use monospace for hex, rub, custom prop values (see implementation https://deploy-preview-85--astrouxds.netlify.app/design-guidelines/color/)

- Use common term for Font color, Black and White

2020-09-18 20:34 UTC, dmcalester commented on _content/components/classification-markings.md
> +| **Do**                     | **Don't**                         |
Use the Do/Don’t format in other components

Provide (placeholder is fine) images for Do/Don’ts. Collaborate with Carmen to provide necessary illustrations

2020-09-18 20:34 UTC, dmcalester commented on _content/components/classification-markings.md
> +### Tag Examples
Add examples. This can be a PNG, don't put time towards adding a second live element at this time.

2020-09-18 20:34 UTC, dmcalester commented on _content/components/classification-markings.md
> +| **Do**                                                                                                                	| **Don't**
Follow the Do/Don’t format
Add placeholder images
Collaborate with Carmen on samples

2020-10-16 15:59 UTC, cskerbo requested changes

2020-10-16 15:59 UTC, cskerbo commented on _content/components/classification-markings.md
> +![Don't: Neglect to mark media such as images and diagrams if they have a different classification from the portion they exist in](/img/components/portion-marking-dont-2.png "Neglect to mark media su
@im-cr This image isn't displaying on the page - can you verify the name is correct and that the resource exists?

2020-10-16 17:30 UTC, im-cr commented on _content/components/classification-markings.md
> +![Don't: Neglect to mark media such as images and diagrams if they have a different classification from the portion they exist in](/img/components/portion-marking-dont-2.png "Neglect to mark media su
@cskerbo removed, talked with Carmen early that item was actually removed from content on her ticket. Updated in the repo now. Thanks

2020-10-16 17:43 UTC, cskerbo commented on _content/components/classification-markings.md
> +![Don't: Neglect to mark media such as images and diagrams if they have a different classification from the portion they exist in](/img/components/portion-marking-dont-2.png "Neglect to mark media su
@im-cr Thanks! You will need to insert a placeholder, blank <figure> element of appropriate size to create a space where the removed "Don't" section was. Take a look at the screenshot below, the Do's/Dont's do not line up like they should:

![Screen Shot 2020-10-16 at 10 36 34 AM](https://user-images.githubusercontent.com/54558554/96290820-14032f80-0f9c-11eb-847c-543702759bf9.png)

2020-10-16 17:55 UTC, cskerbo approved these changes

2020-10-20 18:37 UTC, dmcalester requested changes
Hey Cortney, there are merge conflicts to draft. Please fix ASAP as we have approval from EGS to publish

2020-10-20 20:42 UTC, dmcalester approved these changes

2020-10-20 21:00 UTC, merged

2020-10-20 21:28 UTC, amalyah reviewed
Nothing that should stop the publish, but some questions/comments.

2020-10-20 21:28 UTC, amalyah commented on _content/components/classification-markings.md
> +![Do: Use all-caps for marking text](/img/components/overall-marking-do-1.png "Do: Use all-caps for marking text")
Do we need to write Do in the Do column items when we don't in the Don't columns?

2020-10-20 21:28 UTC, amalyah commented on _content/grm-service-ux-design/grm-dashboard.md
> +<div markdown="1">
This is part of the Classification Marking PR?

2020-10-20 21:28 UTC, amalyah commented on scss/chapters.scss
> +.color,.marking {
.color, .marking
I think it's missing a space?

2020-10-20 21:58 UTC, dmcalester commented on scss/chapters.scss
> +.color,.marking {
It’s valid CSS, but implementing lint/prettier here would be beneficial enforcing coding practices. It’s probably better to do a comprehensive update to all files once a standard has been set.

2020-10-20 22:01 UTC, dmcalester commented on _content/components/classification-markings.md
> +![Do: Use all-caps for marking text](/img/components/overall-marking-do-1.png "Do: Use all-caps for marking text")
I think it might look odd to have the Do above and below include "Do:"

2020-10-20 22:02 UTC, dmcalester commented on _content/grm-service-ux-design/grm-dashboard.md
> +<div markdown="1">
It isn’t. We’ll continue to refine the PR to get more atomic to minimize cross-contamination

2020-10-21 14:48 UTC, amalyah commented on scss/chapters.scss
> +.color,.marking {
Yeah, was just guessing based on the page edit that I saw below it that showed adding the space, but this one didn't have it.