add ag-grid info
RocketCommunicationsInc/astro-uxds pull request #86
Opened 2020-09-22 21:19 UTC by sknep

2020-09-22 21:24 UTC, sknep commented on _content/patterns/table.md
> +* Documentation: https://github.com/RocketCommunicationsInc/astro-ag-Grid/#astro-ag-grid-theme
I prefer this to named links but understand if y'all don't!

2020-09-23 13:14 UTC, amalyah commented on _content/patterns/table.md
> +For more complex tables, we recommend using either the community or enterprise tier of [ag-grid](https://www.ag-grid.com/). While we cannot provide support for ag-grid or its many features, we do pro
- Is "recommend" the right term here?
- ag-grid -> ag-Grid

2020-09-23 13:14 UTC, amalyah commented on _content/patterns/table.md
> +We maintain a [separate repo for the AG-grid Astro theme](https://github.com/RocketCommunicationsInc/astro-ag-Grid). Please visit the following links to get started:
AG-grid -> ag-Grid

2020-09-23 15:20 UTC, dmcalester commented on _content/patterns/table.md
> +For more complex tables, we recommend using either the community or enterprise tier of [ag-grid](https://www.ag-grid.com/). While we cannot provide support for ag-grid or its many features, we do pro
I think recommend is reasonable with the consideration we may expand Astro support to other table/grid packages.

Concur on ag-Grid capitalization case.

2020-09-23 15:24 UTC, dmcalester requested changes
Minor changes. Concur with Amalya’s note on ag-Grid and would prefer to see named links.

2020-09-23 15:24 UTC, dmcalester commented on _content/patterns/table.md
> +* Documentation: https://github.com/RocketCommunicationsInc/astro-ag-Grid/#astro-ag-grid-theme
I would prefer to see named links.

2020-09-24 16:48 UTC, im-cr approved these changes

2020-09-24 18:14 UTC, dmcalester approved these changes

2020-09-29 16:44 UTC, sknep commented
Reminder not to merge this PR all the way to master (or really, even put it on the draft branch) until the ag-grid storybook page is pushed to master (it's on next now, in that repo)

2020-10-13 22:25 UTC, merged