Copyedits and markdown formatting per Astro-723
RocketCommunicationsInc/astro-uxds pull request #88
Opened 2020-10-01 16:39 UTC by sknep

https://rocketcom.atlassian.net/browse/ASTRO-723

2020-10-01 17:23 UTC, sknep commented
It sounds like there are more copyedits coming, hold please

2020-10-01 18:06 UTC, sknep commented
I found some other issues on https://deploy-preview-88--astrouxds.netlify.app/getting-started/developers/ which references some changes to our docs and installation that haven't actually been deployed or published yet. It might best to remove this and leave a note about future updates coming soon, but that makes this page largely unhelpful until the content on astro-components' release/v5 branch lands

2020-10-01 22:40 UTC, dmcalester commented
This is failing in deploy, but not sure why. It doesn’t seem any of the changes to this PR would cause the issue. Are you able to see the console/build log https://app.netlify.com/sites/astrouxds/deploys/5f765a5e7b9bbc0154bcfdc2 ?

2020-10-02 17:07 UTC, sknep commented
OH its because its a draft!

2020-10-02 17:15 UTC, sknep commented
>>> 5:39:15 PM: [build:eleventy] Writing _site/sitemap.xml from ./_content/sitemap.njk.
5:39:15 PM: [build:eleventy] Writing _site/index.html from ./_content/index.md.
5:39:15 PM: [build:eleventy] Error writing templates: (more in DEBUG output)
5:39:15 PM: [build:eleventy] > Having trouble writing template: _site/search/index.html
5:39:15 PM: [build:eleventy]
5:39:15 PM: [build:eleventy] `TemplateWriterWriteError` was thrown
5:39:15 PM: [build:eleventy] > (_includes/search.template.njk)
5:39:15 PM: [build:eleventy]   Template render error: (/opt/build/repo/_includes/_nav.njk) [Line 7, Column 33]
5:39:15 PM: [build:eleventy]   Error: Unable to call `data["url"]["split"]`, which is undefined or falsey

2020-10-02 17:17 UTC, sknep commented
> This is failing in deploy, but not sure why. It doesn’t seem any of the changes to this PR would cause the issue. Are you able to see the console/build log https://app.netlify.com/sites/astrouxds/deploys/5f765a5e7b9bbc0154bcfdc2 ?

Sorry Duncan, I broke the build :) Fixed now!

2020-10-02 17:18 UTC, sknep commented on _content/_data/navigation.json
> +		"url": "/getting-started",
It surprised me that we needed a "url" passed in for nav when that page isn't actually used to build a link. Turns out it's needed as a url segment for the sake of sorting the children in the nav.

2020-10-02 17:40 UTC, cskerbo commented
> I found some other issues on https://deploy-preview-88--astrouxds.netlify.app/getting-started/developers/ which references some changes to our docs and installation that haven't actually been deployed or published yet. It might best to remove this and leave a note about future updates coming soon, but that makes this page largely unhelpful until the content on astro-components' release/v5 branch lands

2020-10-02 19:13 UTC, cskerbo commented
> ### Getting Started  
> You can import Astro UXDS Web Components to an existing application using npm and litElement. Detailed instructions for using Astro components are available in the project’s README.  
>   
> If you’re considering a non-Web Component Astro implementation, <strike>directions for including Astro CSS and other static assets are available here. For those developing offline applications, be sure to review the special considerations for offline Astro assets. </strike> directions for this process will be available soon.

Under the getting started section for Development, we need to make the change above. We can create a separate ticket to ensure this is changed back once the v5 branch is released.

2020-10-02 22:39 UTC, cskerbo requested changes
> **Getting Started**
> You can import Astro UXDS Web Components to an existing application using npm and litElement. Detailed instructions for using Astro components are available in the project’s README.
> 
> If you’re considering a non-Web Component Astro implementation, <strike>directions for including Astro CSS and other static assets are available here. For those developing offline applications, be sure to review the special considerations for offline Astro assets.</strike> directions for this process will be available soon.

Under the getting started section for Development, we need to make the change above. We can create a separate ticket to ensure this is changed back once the v5 branch is released.

2020-10-05 22:21 UTC, cskerbo approved these changes

2020-10-06 16:24 UTC, sknep commented
@im-cr do you wanna take a look at this branch and see where it stands compared to your work before i merge it in?

2020-10-06 22:43 UTC, sknep commented
@dmcalester please approve when you get a moment

2020-10-06 23:34 UTC, dmcalester commented
> These examples use a previous release of Astro, and are not intended as boilerplates for building new applications. See below for easy ways to get started building Astro web applications.

:D

2020-10-06 23:36 UTC, dmcalester approved these changes
Approved with two minor case changes to titles.

2020-10-06 23:36 UTC, dmcalester commented on _content/getting-started/_readme.md
> +**Supported browsers**
Title case

2020-10-06 23:36 UTC, dmcalester commented on _content/getting-started/_readme.md
>  ### Offline access
Title case

2020-10-07 15:40 UTC, merged